service: my-service # NOTE: update this with your service name

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  region: cn-northwest-1
  endpointType: regional
##  profile: zhy
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: arn:aws-cn:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/pets-store

functions:
  hello:
    handler: functions/hello-world.handler
    events: 
      - http:
          path: hello
          method: get
          authorizer: custom-authorizer

  get-pets:
    handler: functions/get-pets.handler
    events: 
      - http:
          path: pets
          method: get

  auth-user:
    handler: functions/auth-user.handler
    events: 
      - http: 
          path: /auth
          method: post
          private: true

  custom-authorizer: 
    handler: functions/custom-authorizer.handler

resources:
  Resources:
    petsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pets-store
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        
